### PR TITLE
Korean War (Arctic) and SUEZ Crisis (Desert) 1950s Units

### PR DESCRIPTION
**Pull request by rwalker959**
No Entry Error on non-dismounted Units that I can't figure out. Rik to the rescue?

**This pull request will:**
- Add Korean War Units to WW2 Repo

### CODE REVIEW

**Comment by Neciota** [comment]
Post a screenie of the error. I am on holiday at the moment.

**Comment by rwalker959** [comment]
> Post a screenie of the error. I am on holiday at the moment.

Units are there but not picking up the class name :(

https://imgur.com/a/ygiSgKG

https://imgur.com/a/ex6avI6

**Comment by Neciota** [comment]
Replace `CATEGORY(TWC_Infantry_Arctic)` with `CATEGORY(TWC_Infantry_Regular_Arctic)`

**Comment by rwalker959** [comment]
That fixed it thanks! Now building fine and in game but failing on Github :(

**Pull request merged**
